services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\WvFileCleanup\:
    resource: '../Classes/*'

  WebVision\WvFileCleanup\Command\EmptyRecyclerCommand:
    tags:
      - name: console.command
        command: 'wv_file_cleanup:emptyrecycler'
        schedulable: true

  WebVision\WvFileCleanup\Command\CleanupCommand:
    tags:
      - name: console.command
        command: 'wv_file_cleanup:cleanup'
        schedulable: true

  WebVision\WvFileCleanup\Listener\ResourceStorageListener:
    tags:
      - name: event.listener
        method: 'postFileMove'
        event:  TYPO3\CMS\Core\Resource\Event\AfterFileMovedEvent

  WebVision\WvFileCleanup\Controller\CleanupController:
    tags: [ 'backend.controller' ]

